frontend/src/App.tsx
frontend/src/components/Cell/index.tsx
frontend/src/components/Grid/index.tsx
frontend/src/types/cellData.ts

Changes:
- fixed `key` error in console
- moved `onEdited` outside `Cell` data props

Grid, Cell fixes

---

backend/api.py
backend/app.py
backend/app_types.py
backend/backtracking.py
backend/generate.py
backend/helpers.py
backend/solve.py
backend/solve_questions.py

Generate answers and questions

---

frontend/.eslintrc.json
frontend/package-lock.json
frontend/package.json
frontend/src/App.tsx
frontend/src/components/Button/styles.scss
frontend/src/components/Cell/corner.ts
frontend/src/components/Cell/index.tsx
frontend/src/components/Cell/styles.scss
frontend/src/components/Grid/index.tsx
frontend/src/components/Label/styles.scss
frontend/src/components/Tab/styles.scss
frontend/src/components/TextField/styles.scss
frontend/src/icons/LeftArrow/index.tsx
frontend/src/icons/LeftArrow/styles.scss
frontend/src/icons/Square/index.tsx
frontend/src/icons/Square/styles.scss
frontend/tsconfig.json

Fixes #37 
Вирішив не додавати aliases, вони, як мінімум зараз, не потрібні. Замість них додав`baseUrl`.
Також додав налаштування eslint. Буду радий почути які правила ще слід додати, які виключити. Перед review, потрібно встановити нові dependencies: `npm i`

Aliases and linter

---

frontend/src/components/Button/styles.scss

Replace values with variables in `Button`

---

frontend/src/components/Layout/styles.scss

Simplify import path

---

frontend/src/appConstants.ts
frontend/src/store/index.ts

Move actions to code

---

frontend/.eslintrc.json

Turn off `@typescript-eslint/no-non-null-assertion`

---

frontend/src/store/index.ts

Є така проблема, що тип матриці у компоненті `Grid` не такий як у стейті, можливо нам потрібно змінити тип у стейті, чи ми будемо парсити матрицю, щоб вона підходила для `Grid`y?
Fixes #55

Fill erase reducers

---

frontend/src/store/index.ts

Редюсери для showConfirmation, dismissConfirmation

---

frontend/src/store/index.ts

Редюсери для switchToDrawing, switchToDrawing, switchToAnswer, switchToPuzzle

---

backend/app.py
backend/app_types.py
backend/generate.py
backend/solve.py

Fixes #75 
Створив окремий тип для відповіді з сервера.

Adapt api response

---

frontend/src/components/Button/index.tsx
frontend/src/components/Cell/index.tsx
frontend/src/components/Dialog/index.tsx
frontend/src/components/Grid/index.tsx
frontend/src/components/Label/index.tsx
frontend/src/components/Layout/index.tsx
frontend/src/components/Loader/index.tsx
frontend/src/components/QuestionPanel/index.tsx
frontend/src/components/Tab/index.tsx
frontend/src/components/TextField/index.tsx
frontend/src/components/TitleLabel/index.tsx
frontend/src/icons/Square/index.tsx

Export all type props

---

backend/app.py
backend/app_types.py

Fix solve endpoint response

---

frontend/src/components/Cell/index.tsx
frontend/src/components/Cell/styles.scss
frontend/src/components/Grid/index.tsx

Disable editable state of non-clickable(editable) cell

---

frontend/src/components/Tab/index.tsx

Sort type and props in `Tab`

---

frontend/src/views/DrawingOrErasingView/index.tsx
frontend/src/views/DrawingOrErasingView/styles.scss

Animation of appearance / disappearance of buttons on the initial view

---

frontend/src/components/App/index.tsx
frontend/src/views/DrawingOrErasingView/index.tsx

Replace dispatch with callbacks

---

backend/backtracking.py
backend/generate.py
backend/helpers.py
backend/solve.py
frontend/src/store/helpers.ts

Fixes #98 
Якщо у клітинки нема сусідів, то вона не буде вважатися окремим словом в алгоритмі генерації, через що слова будуть пусті, що не було передбачено в алгоритмі розв'язування і викликало помилку. Зробив так що це не призводить до помилки і повертається `None`, тому, що мені здається логічним що одна клітинка - не слово, в цьому випадку ще треба напевно зробити щоб кнопка 'generate questions' не показувалась коли заповнена одна клітинка чи по діагоналі.
Але можливо треба зробити, щоб одна клітинка рахувалась за слово.

Fix no adjacent cells error

---

frontend/src/components/Layout/index.tsx

Вирівняти заголовок сторінки з графікою

---

frontend/src/components/App/index.tsx
frontend/src/store/index.ts

Confirmation `Dialog`

---

frontend/src/appConstants.ts
frontend/src/store/index.ts

Use `API_URL` from `.env` instead of constant

---

backend/generate.py
frontend/src/store/helpers.ts

Count one-cell words as words across

---

backend/backtracking.py

Ban repeating words 

---

backend/api.py
backend/generate.py

Normalize generated questions

---

backend/api.py

Sorting api responses by part of speech

---

frontend/src/components/App/index.tsx

Do not display the dialog if no question has been entered yet

---

frontend/src/components/App/index.tsx

Tab label change: `Answer` -> `Answers`

---

backend/api.py
frontend/.env

Fix `/solve` endpoint when undefined tags come from API

---

frontend/src/store/index.ts

Fix failed view shown after retrying request to the api

---

frontend/src/components/Tab/styles.scss
frontend/src/components/Tabs/index.tsx
frontend/src/components/Tabs/styles.scss

Vertical margin between tab and grid

---

frontend/src/components/App/styles.scss
frontend/src/components/Dialog/styles.scss
frontend/src/components/Label/styles.scss

Fix distances between labels and other components

---

frontend/src/components/App/index.tsx

Hide questions label and button when the dialog is open

---

backend/api.py

Filter questions that start not with letters

---

backend/api.py

Words from API must contain only Latin characters

---

backend/api.py

Replace `API_PATH` from `datamuse` to `onelook`

---

backend/api.py
backend/helpers.py

Check if word returned from api fits the pattern

---

backend/api.py
backend/solve.py

Fixes #158 
Проблема справді була в тому, що апі не розпізнавало спеціальних знаків, тому тепер в питаннях, які передаються в апі залишаються тільки букви, цифри, пробіли та перенесення рядка.

Normalize user questions

---

frontend/src/components/App/index.tsx

Fix behaviour on `requestFailed`

---

backend/generate.py

Fix word changing its direction when generating questions
